on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.6'
      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - run: flutter build windows
      uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: AppName-${{github.ref_name}}-windows.zip
          directory: build/windows/runner/Release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/windows/runner/Release/AppName-${{github.ref_name}}-windows.zip"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}